import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useContext } from 'react'
import internal from 'stream'
import { useUserContext } from '../context/userContext'
import styles from '../styles/Home.module.css'

type Props = {
  data: {
    limit: number,
    offset: number,
    items: Array<{
      id: number,
      name: String,
      slug: String,
      description: String,
      created: String,
      updated: String,
    }>
  }
};

type Context = any;

export default function Home( { data }: Props ) {
  const loginContext = useUserContext();

  return (
    <div className={styles.container}>
      <Head>
        <title>Viðburðasíðan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Viðburðasíðan
        </h1>

        <h2 className={styles.description}>
          Viðburðir á næstunni
        </h2>

        <section>
          <ul>
            {data.items.length === 0 && (
              <li>Engir viðburðir</li>
            )}
            {data.items.length > 0 && data.items.map((event, i) => {
              return (
                <li key={i}>
                  <Link href={`/${event.id}`}><a>{event.name}</a></Link>
                  <p>{event.description}</p>
                </li>
              )
            })}
         </ul>
        </section>

        <footer className={styles.footer}>
          <Link href='/'><a>Forsíða</a></Link>
          {
            loginContext.state.login.login ? <p>Skráður inn sem <b>{loginContext.state.login.user.user.name}</b></p> : <Link href='/login'>Innskráning</Link>
          }
          {
            loginContext.state.login.login ? <button onClick={loginContext.toggleLogin}>Útskrá</button> : <Link href='/register'>Nýskráning</Link>
          }
        </footer>
      </main>
    </div>
  )
}

export async function getServerSideProps(context: Context) {
  const res = await fetch(`https://vef2-20222-v3-synilausn.herokuapp.com/events`);
  const data = await res.json();

  if (!data) {
    return {
      notFound: true,
    }
  }

  return {
    props: {
      data,
    },
  }
}
